[package]
name = "rusty-systems"
description = "A library for procedurally generating content using L-Systems"
version = "0.3.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/TheRiver/rusty-systems/"
keywords = ["grammar", "l-systems", "procedural", "generation"]

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
rand = "0.8"

[dev-dependencies]
tiny-skia = "0.11"