name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency:
      group: "rust build"
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests for default features
      run: cargo test --verbose
    - name: Run tests for all features
      run: cargo test --verbose --all-features
